; ===========================================
; BAME Battery Monitor - PlatformIO Config
; ===========================================

; --- Config partagee ---
[env]
platform = atmelavr
framework = arduino
monitor_speed = 115200

lib_deps =
    Wire
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5
    robtillaart/INA226@^0.6.6

; --- Prototypage : Arduino Nano USB-C (ATmega328P) ---
[env:nano]
board = nanoatmega328new
upload_protocol = arduino
; port auto-detecte
build_flags = -DBAME_DEBUG=0 -flto

; --- Production : USBasp + board compact ---
[env:prod]
board = ATmega328PB
board_build.mcu = atmega328pb
board_build.f_cpu = 16000000L
upload_protocol = usbasp
upload_flags = -B 4
build_flags = -DBAME_DEBUG=0 -flto
